import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/modules/navbar/page'
import Footer from '@/modules/footer/page'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
